services:
  mongo:
   image: mongo:7.0
   environment:
    ROOT_USERBAME: username
    ROOT_PASSWORD: password
   ports: 
    - 28017:27017
   volumes:
    - mongodata:/data/db
volumes:
  mongodata:
   driver: local